### ISSUE TITLE
X-Frame-Options prevent iFrame

### ISSUE THREAD

**Issue by ForrestMcIntyre** [ForrestMcIntyre/scraper#1]
### iFrame Issue

X-Frame-Options header is set to DENY or SAMEORIGIN by most popular sites preventing the preview and click to see what selectors you are going to scrape

Console Error:

> Refused to display 'https://www.google.com/?gws_rd=ssl' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by ForrestMcIntyre** [comment]
@thomaswilburn  https://github.com/ForrestMcIntyre/scraper/blob/master/views/templates/scraper.html#L13

**Comment by thomaswilburn** [comment]
You may be able to get around this by proxying the request through your Hapi server, which can obviously serve content with whatever headers you want.
